workflows:
  ios-publish-fastlane:
    name: iOS Publish Fastlane
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - bundle install
      - bundle exec fastlane snapshot
    artifacts:
      - ./*.ipa
      - ./*.dSYM.zip
      - ./screenshots
