definitions:
  environment_versions: &environment_version
    vars:
      XCODE_PROJECT: "Codemagician.xcodeproj"
      XCODE_SCHEME: "Codemagician"
      BUNDLE_ID: "com.rudrankriyam.codemagician"

workflows:
  testing-workflow:
    name: Testing Workflow
    working_directory: Codemagician
    environment:
      <<: *environment_version
    scripts:
      - name: Build project
        script: |
          xcodebuild build -project "$XCODE_PROJECT" -scheme "$XCODE_SCHEME" CODE_SIGN_INDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
      - name: Test project
        script: |
          xcode-project run-tests \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME" \
        test_report: build/ios/test/*.xml
